-- AlterTable
ALTER TABLE "Orders" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "lastModified" SET DATA TYPE TIMESTAMPTZ(6);
